### ISSUE TITLE
Cirrus CI checking failed  strangely on  federa 30 and centos 8_1

### ISSUE THREAD

**Issue by chunfuwen** [avocado-framework/avocado-vt#2615]
One example:https://github.com/avocado-framework/avocado-vt/pull/2606/files
I believe the PR change don't touch  bootstrap, but Cirrus CI checking failed

**Comment by chunfuwen** [comment]
one more,https://github.com/avocado-framework/avocado-vt/pull/2599

**Comment by clebergnu** [comment]
@chunfuwen these seem to be caused by the source branches being too distant from master, which contains two fixes:

* https://github.com/avocado-framework/avocado-vt/pull/2612
* https://github.com/avocado-framework/avocado-vt/pull/2604

For instance, on https://github.com/yalzhang/avocado-vt/tree/add_del_mac, you'll see:

```
This branch is 1 commit ahead, 21 commits behind avocado-framework:master.
```

A rebase on those branches should fix the failures.  I'm pretty confident that rebasing should do it, but if it doesn't please reopen this issue. Thanks.

**Comment by lento-sun** [comment]
Hi @clebergnu I rebase https://github.com/avocado-framework/avocado-vt/pull/2599 to latest upstream master branch, and now it has:
`This branch is 1 commit ahead of avocado-framework:master.`
in https://github.com/lento-sun/avocado-vt/tree/get_cp_xml
But the PR still failed with some checks, could you please have a check? thx
